book_share_demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # index
    path('', TemplateView.as_view(template_name='index.html', extra_context={'current_page': ''}), name='index'),
    # users
    path('user/', include('users.urls', namespace='users')),
    # books
    path('book/', include('books.urls', namespace='books')),
    # comments
    path('comment/', include('comments.urls', namespace='comments')),
    # search
    path('search/', include('haystack.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
# encoding: utf-8
"""
@author: Sunmouren
@contact: sunxuechao1024@gmail.com
@time: 2018/9/22 12:01
@desc: 
"""

from django.urls import path

from .views import BookListView, BookDetailView, UploadBookView, EditBookView, PreviewPdfView


app_name = 'books'

urlpatterns = [
    path('upload/', UploadBookView.as_view(), name='upload_book'),
    path('<int:book_id>/edit/', EditBookView.as_view(), name='edit_book'),
    path('list/', BookListView.as_view(), name='book_list'),
    path('detail/<int:book_id>/', BookDetailView.as_view(), name='book_detail'),
    path('preview/pdf/<int:book_id>/', PreviewPdfView.as_view(), name='preview_pdf'),
]

comments/urls.py
# encoding: utf-8
"""
@author: Sunmouren
@contact: sunxuechao1024@gmail.com
@time: 2018/9/28 20:17
@desc: 
"""

from django.urls import path

from .views import SubmitCommentAjax, LikeCommentAjax, DeleteCommentAJax, HotCommentListView

app_name = 'comments'

urlpatterns = [
    path('hot/list/', HotCommentListView.as_view(), name='hot_comment'),
    path('submit/', SubmitCommentAjax.as_view(), name='submit_comment'),
    path('like/', LikeCommentAjax.as_view(), name='submit_like'),
    path('delete/', DeleteCommentAJax.as_view(), name='submit_delete'),
]

users/urls.py
# encoding: utf-8
"""
@author: Sunmouren
@contact: sunxuechao1024@gmail.com
@time: 2018/9/22 12:13
@desc: 
"""
from django.urls import path
from .views import UserProfileView, UserListView, FollowUserAjax,\
    UserLoginView, UserRegisterView, UserLogoutView, ModifyUserProfileView


app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='user_profile'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('follow/', FollowUserAjax.as_view(), name='follow_user'),
    path('<int:user_id>/modify/', ModifyUserProfileView.as_view(), name='modify_profile'),
]

books/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from users.models import UserProfile


class Category(models.Model):
    """
    分类表
    """
    name = models.CharField(max_length=32, verbose_name='分类名')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ('-name',)

    def __str__(self):
        return self.name


class Book(models.Model):
    """
    图书表
    """
    name = models.CharField(max_length=128, verbose_name='书名')
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 blank=True, null=True,
                                 related_name='category_books',
                                 verbose_name='分类')
    cover_picture = models.ImageField(upload_to='image/book/picture',
                                      default='image/default.jpg',
                                      verbose_name='封面图')
    desc = models.TextField(verbose_name='简介')
    upload_user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                    on_delete=models.CASCADE,
                                    related_name='upload_books',
                                    verbose_name='上传者')
    pdf = models.FileField(upload_to='resource/pdf', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='上传时间')

    class Meta:
        verbose_name = '图书'
        verbose_name_plural = verbose_name
        ordering = ('-created',)

    def get_absolute_url(self):
        """
        :return: 图书绝对路径
        """
        return reverse('books:book_detail', args=[self.id])

    def __str__(self):
        return self.name

users/forms.py
# encoding: utf-8
"""
@author: Sunmouren
@contact: sunxuechao1024@gmail.com
@time: 2018/10/3 10:51
@desc: 
"""
from django import forms

from .models import UserProfile


class UserLoginForm(forms.Form):
    """
    登录验证表单
    """
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)


class UserRegisterForm(forms.Form):
    """
    注册验证表单
    """
    email = forms.EmailField(required=True)
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)


class ModifyUserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['avatar', 'nickname', 'signature']

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>图书分享</title>

    <!-- Bootstrap core CSS -->
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/offcanvas.css' %}" rel="stylesheet">
      <link  href="{% static 'css/animate.min.css' %}" rel='stylesheet'/>
      <link href="{% static 'css/user-book.css' %}" rel="stylesheet">
      <link href="{% static 'css/font-awesome.min.css' %}" rel='stylesheet'>
      {% block css %}{% endblock %}
  </head>

  <body style="background-color: #f4f5f6">

    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
      <div class="container">
          <a class="navbar-brand" href="{% url 'index' %}">在线图书分享</a>
          <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="navbar-collapse  offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item {% ifequal current_page '' %}active{% endifequal %}">
                <a class="nav-link " href="{% url 'index' %}">首页</a></li>
              <li class="nav-item {% ifequal current_page 'book_list' %}active{% endifequal %}" >
                <a class="nav-link" href="{% url 'books:book_list' %}">图书</a>
              </li>
              <li class="nav-item {% ifequal current_page 'user_list' %}active{% endifequal %}">
                <a class="nav-link " href="{% url 'users:user_list' %}">书友</a>
              </li>

            {% if request.user.is_authenticated %}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">关注</a>#}
{#                </li>#}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="{{ request.user.avatar.url }}" alt="" class="mr-2 rounded" style="width: 20px; height: 20px;">
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                      <a class="dropdown-item" href="{% url 'users:user_profile'  request.user.id %}">我的主页</a>
                      <a class="dropdown-item" href="{% url 'books:upload_book' %}">上传图书</a>
                      <a class="dropdown-item" href="{% url 'users:user_logout' %}">退出登录</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:user_register' %}">注册</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:user_login' %}">登录</a>
                </li>
            {% endif %}
            </ul>


            <form class="form-inline my-2 my-lg-0" action="{% url 'haystack_search' %}">
              <input class="form-control mr-sm-2" id="unit" type="search" name="q" placeholder="这里输入关键词..." aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜书</button>
            </form>
          </div>
      </div>
    </nav>

{#    <div class="nav-scroller bg-white box-shadow">#}
{#      <nav class="nav nav-underline container" >#}
{#        <a class="nav-link active" href="#">发现</a>#}
{#        <a class="nav-link" href="#">#}
{#            图书#}
{#        </a>#}
{#        <a class="nav-link" href="#">#}
{#            关注#}
{#            <span class="badge badge-pill bg-light align-text-bottom">27</span>#}
{#        </a>#}
{#        <a class="nav-link" href="#">书友</a>#}
{#        <a class="nav-link" href="#">Link</a>#}
{#        <a class="nav-link" href="#">Link</a>#}
{#        <a class="nav-link" href="#">Link</a>#}
{#        <a class="nav-link" href="#">Link</a>#}
{#        <a class="nav-link" href="#">Link</a>#}
{#      </nav>#}
{#    </div>#}

    <main role="main">
      {% block main %}
      
      {% endblock %}


       {% block modal %}

       {% endblock %}
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-slim.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/holder.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/offcanvas.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap-notify.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/app.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
    </script>
    {% block custom_js %}
    
    {% endblock %}
  </body>
</html>

templates/book-detail.html
{% extends "base.html" %}

{% load comment_tags %}

{% block main %}
    <div class="container">

        <div class="my-3 p-3 bg-white rounded box-shadow">
            <div class="row">
                <div class="col-md-2">
                    <div class="card bg-dark text-white d-none d-md-block">
                      <img class="card-img" src="{{ book.cover_picture.url }}" alt="Card image">
                    </div>
                </div>
                <div class="col-md-10">
                    <div class="d-flex flex-column">
                      <div class="p-1"> <span class="text-danger">书名:</span> <span class="ml-2 text-success">{{ book.name }}</span> </div>
                      <div class="p-1 d-none d-md-block">
                          <span class="text-danger">简介:</span> <span class="ml-2 text-success">{{ book.desc }}</span>
                      </div>
                      <!--小屏幕显示模块-->
                      <div class="p-1 d-block d-sm-none">
                          <a class="text-danger" href="#description" data-toggle="collapse" aria-expanded="false" aria-controls="description">点击显示简介</a>
                      </div>
                      <div class="p-1 collapse" id="description">
                          <div class="card card-body">
                              {{ book.desc }}
                          </div>
                      </div>
                        <div class="p-1"> <span class="text-danger">上传者:</span> <a href="{{ book.upload_user.get_absolute_url }}"><span class="ml-2 text-success">{{ book.upload_user }}</span></a> </div>

                        <!--小屏幕显示模块结束-->
                    </div>
                </div>
            </div>
        </div>

        <div class="nav-scroller bg-white box-shadow" id="recent">
            <nav class="nav nav-underline container" >
                <a class="nav-link" href="#comment-form-0" data-toggle="collapse" aria-expanded="false" aria-controls="comment-form">
                   <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 写书评</a>
               <a class="nav-link {% ifequal 'recent' data %}active text-success{% endifequal %}" href="?data=recent">
                   <i class="fa fa-comment-o" aria-hidden="true"></i> 最新书评</a>
               <a class="nav-link {% ifequal 'hot' data %}active text-success{% endifequal %}" href="?data=hot">
                   <i class="fa fa-comments-o" aria-hidden="true"></i> 热门书评</a>

               <a class="nav-link" href="{% url 'books:preview_pdf' book.id %}"><i class="fa fa-eye" aria-hidden="true"></i> 预览</a>
                {% if request.user.is_authenticated %}
                     <a class="nav-link" href="{{ book.pdf.url }}" target="_blank" download="" data-id="274" title="">
                         <i class="fa fa-download" aria-hidden="true"></i> 下载</a>
                {% else %}
                     <a class="nav-link" href="{% url 'users:user_login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> 登录（下载）</a>
                {% endif %}
            </nav>
        </div>

        <!-- comment form -->
        <div class="my-3 p-3 bg-white rounded box-shadow collapse clearfix" id="comment-form-0">
            <form>
                <div class="form-group">
                    <textarea class="form-control" id="message-text-0" data-login="{% if not request.user.is_authenticated %}un{% endif %}login" placeholder="写下你的评论..."></textarea>
                </div>
                <button type="button" class="btn btn-sm btn-outline-success float-right " onclick="submitComment({{ book.id }}, 0)">发 送</button>
                <button type="button" class="btn btn-sm btn-outline-secondary float-right mr-3" href="#comment-form-0" data-toggle="collapse" aria-expanded="false" aria-controls="comment-form">取消</button>
            </form>
        </div>

        <!-- book recent comments data-->
         <div class="my-3 p-3 bg-white rounded box-shadow">
             <h6 class="border-bottom border-gray pb-2 mb-0" id="comment-info">
                {{ info }}书评(<span id="comment-count">{{ comment_count }}</span>)
             </h6>

             <div id="comment-list">
                {% for comment in comments %}
                    {% include 'comment-item.html' %}
                {% endfor %}
            </div>

            <!-- fake comment -->
            <div class="media text-muted pt-3">
              <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">@username</strong>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
              </p>
            </div>
            <div class="media text-muted pt-3">
              <img data-src="holder.js/32x32?theme=thumb&bg=e83e8c&fg=e83e8c&size=1" alt="" class="mr-2 rounded">
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">@username</strong>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
              </p>
            </div>
            <div class="media text-muted pt-3">
              <img data-src="holder.js/32x32?theme=thumb&bg=6f42c1&fg=6f42c1&size=1" alt="" class="mr-2 rounded">
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">@username</strong>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
              </p>
            </div>
        </div>
    </div>
{% endblock %}

templates/edit-book.html
{% extends "base.html" %}

{% block main %}
    <div class="container">
        <div class="my-3 p-3 bg-white rounded box-shadow">
         <h6 class="border-bottom border-gray pb-2 mb-3">
             <a href="{{request.user.get_absolute_url }}"><i class="fa fa-reply" aria-hidden="true"></i> 主页</a>-编辑图书</h6>
            <form method="post" enctype="multipart/form-data" action="{% url 'books:edit_book' book.id %}">
                {% csrf_token %}
              <div class="form-group row">
                <label for="id_cover_picture" class="col-sm-1 col-form-label">封面图</label>
                <div class="col-sm-11">
                    <a href="{{ book.cover_picture.url }}">目前:{{ book.cover_picture.url }}</a>
                </div>
              </div>

              <div class="form-group row">
                <label for="id_cover_picture" class="col-sm-1 col-form-label">修改</label>
                <div class="col-sm-10">
                    <input type="file" class="form-control-file {% if 'cover_picture' in invalid_keys %}is-invalid{% endif %}" id="id_cover_picture" name="cover_picture">
                </div>
              </div>

              <div class="form-group row">
                <label for="id_name" class="col-sm-1 col-form-label">书名</label>
                <div class="col-sm-11">
                  <input type="text" class="form-control {% if 'name' in invalid_keys %}is-invalid{% endif %}" id="id_name" required name="name" value="{{ book.name }}">
                </div>
              </div>
              <div class="form-group row">
                <label for="id_desc" class="col-sm-1 col-form-label">简介</label>
                <div class="col-sm-11">
                    <textarea class="form-control {% if 'desc' in invalid_keys %}is-invalid{% endif %}" id="id_desc" rows="5" required name="desc" >{{ book.desc }}</textarea>
                </div>
              </div>

                <div class="form-group row">
                    <label class="col-sm-1" for="id_category">分类</label>
                    <div class="col-sm-2">
                        <select class="form-control" id="id_category" name="category">
                            <option selected>---------</option>
                            {% for category in categories %}
                                <option {% ifequal category book.category %}selected{% endifequal %} value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                </div>

              <div class="form-group row">
                <div class="col-sm-12 mt-3">
                  <button type="submit" class="btn btn-success">保存修改</button>
                </div>
              </div>
            </form>

            {% if edit_form.errors.items %}
               <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
                    {% for key, error in edit_form.errors.items %}
                        {{ error }}
                    {% endfor %}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
           {% endif %}
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        {% ifequal 'ko' status %}
            $(function () {
                tips('保存失败~', 'danger');
                return true;
            });
        {% endifequal %}

        {% ifequal 'ok' status %}
            $(function () {
                tips('保存成功~', 'success');
                return true;
            });
        {% endifequal %}
    </script>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block main %}
    <div class="container">
       <div class="my-3 p-3 bg-white rounded box-shadow">
            <form action="{% url 'users:user_login' %}" method="post">
              <div class="form-group">
                <label for="id_email">邮箱地址</label>
                <input type="email" class="form-control {% if 'email' in invalid_keys %}is-invalid{% endif %}" id="id_email" name="email" aria-describedby="emailHelp" required placeholder="输入邮箱">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="id_password">登录密码</label>
                <input type="password" class="form-control {% if 'password' in invalid_keys %}is-invalid{% endif %}" id="id_password" name="password" required placeholder="输入密码">
              </div>
              <div class="form-group">
                <label>还没有账号？<a href="{% url 'users:user_register' %}">点击注册</a></label>
              </div>
                {% csrf_token %}
              <button type="submit" class="btn btn-success">登录</button>
            </form>
           {% if msg or user_login_form.errors.items %}
               <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
                    {% for key, error in user_login_form.errors.items %}
                        {{ error }}
                    {% endfor %}
                    {{ msg }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
           {% endif %}
       </div>
    </div>
{% endblock %}

templates/preview-pdf.html
{% extends "base.html" %}

{% load staticfiles %}

{% block main %}
{#    <div class="container">#}
{#        <span id="page_count"></span>#}
{#    </div>#}

    <div class="container">

        <div class="row ">
            <div class="col-sm-12 col-md-12 p-2">
                <h6 class="border-bottom mb-2 mt-2 border-gray">
                    <a href="{{ book.get_absolute_url }}"><i class="fa fa-reply" aria-hidden="true"></i> 返回</a>
                    - {{ book.name }}
                </h6>
                <div class="embed-responsive embed-responsive-4by3">
                 <iframe class="embed-responsive-item pdf" src="{{ book.pdf.url }}"></iframe>
                </div>
            </div>


        </div>
    </div>

{% endblock %}

{% block custom_js %}
     <script type="text/javascript" src="{% static 'js/pdf/jquery.media.js' %}"></script>
     <script type="text/javascript">
        $(function() {
            $('a.media').media();
        });
     </script>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block main %}
    <div class="container">
       <div class="my-3 p-3 bg-white rounded box-shadow">
            <form action="{% url 'users:user_register' %}" method="post">
              <div class="form-group">
                <label for="id_email">邮箱注册</label>
                <input type="email" class="form-control {% if 'email' in invalid_keys %}is-invalid{% endif %}" id="id_email" name="email" aria-describedby="emailHelp" required placeholder="输入邮箱">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="id_password1">设置密码</label>
                <input type="password" class="form-control {% if 'password1' in invalid_keys %}is-invalid{% endif %}" id="id_password1" name="password1" required placeholder="输入密码">
              </div>
                <div class="form-group">
                <label for="id_password2">确认密码</label>
                <input type="password" class="form-control {% if 'password2' in invalid_keys %}is-invalid{% endif %}" id="id_password2" name="password2" required placeholder="确认密码">
              </div>
            {% csrf_token %}
              <button type="submit" class="btn btn-success">注册</button>
            </form>
           {% if msg or user_register_form.errors.items %}
               <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
                    {% for key, error in user_register_form.errors.items %}
                        {{ error }}
                    {% endfor %}
                    {{ msg }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
           {% endif %}
       </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        {% ifequal 'ok' status %}
            $(function () {
                tips('注册成功，即将跳转到登录界面~', 'success');
                setTimeout(function () {
                    window.location.href = '/user/login/';
                }, 3500);
            });        
        {% endifequal %}
        
    </script>
{% endblock %}

templates/upload-book.html
{% extends "base.html" %}

{% load staticfiles %}

{% block css %}
    <link href="{% static 'css/fileinput.min.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
    <div class="container">
        <div class="my-3 p-3 bg-white rounded box-shadow">
         <h6 class="border-bottom border-gray pb-2 mb-3">
             <a href="{{request.user.get_absolute_url }}"><i class="fa fa-reply" aria-hidden="true"></i> 主页</a>-上传图书</h6>
            <form method="post" enctype="multipart/form-data" action="{% url 'books:upload_book' %}">
                {% csrf_token %}
              <div class="form-group row">
                <label for="id_cover_picture" class="col-sm-1 col-form-label">封面图</label>
                <div class="col-sm-11">
                    <input type="file"
                           class="form-control-file {% if 'cover_picture' in invalid_keys %}is-invalid{% endif %}"
                           data-msg-placeholder="请选择一张图片作为图书封面"
                           id="id_cover_picture" required name="cover_picture">
                </div>
              </div>
                <div class="form-group row">
                <label for="id_pdf" class="col-sm-1 col-form-label">PDF</label>
                <div class="col-sm-11">
                    <input type="file"
                           class="form-control-file {% if 'pdf' in invalid_keys %}is-invalid{% endif %}"
                           data-msg-placeholder="请选择的电子书格式为PDF"
                           id="id_pdf"
                           required name="pdf">
                </div>
              </div>

              <div class="form-group row">
                <label for="id_name" class="col-sm-1 col-form-label">书名</label>
                <div class="col-sm-11">
                  <input type="text" class="form-control {% if 'name' in invalid_keys %}is-invalid{% endif %}" id="id_name" required name="name">
                </div>
              </div>
              <div class="form-group row">
                <label for="id_desc" class="col-sm-1 col-form-label">简介</label>
                <div class="col-sm-11">
                    <textarea class="form-control {% if 'desc' in invalid_keys %}is-invalid{% endif %}" id="id_desc" rows="5" required name="desc"></textarea>
                </div>
              </div>

                <div class="form-group row">
                    <label class="col-sm-1" for="id_category">分类</label>
                    <div class="col-sm-2">
                        <select class="form-control" id="id_category" name="category">
                            <option selected>---------</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

              <div class="form-group row">
                <div class="col-sm-12 mt-3">
                  <button type="submit" class="btn btn-success">确认上传</button>
                </div>
              </div>
            </form>

            {% if upload_form.errors.items %}
               <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
                    {% for key, error in upload_form.errors.items %}
                        {{ error }}
                    {% endfor %}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
           {% endif %}
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        {% ifequal 'ko' status %}
            $(function () {
                tips('上传失败~', 'danger');
                return true;
            });
        {% endifequal %}
    </script>
    <script type="text/javascript" src="{% static 'js/fileinput.min.js' %}"></script>
    <script type="text/javascript">
        $("#id_cover_picture").fileinput({
            showUpload: false,
            dropZoneEnabled: false,
            allowedFileExtensions: ["jpg", "png", "gif"],

        });

        $("#id_pdf").fileinput({
            showUpload: false,
            dropZoneEnabled: false,
            allowedFileExtensions: ["pdf"],
        });
    </script>
{% endblock %}